"""Added new columns to User model

Revision ID: 202797cfb47c
Revises: 784e7d8665fc
Create Date: 2025-03-05 09:23:01.681449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202797cfb47c'
down_revision = '784e7d8665fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_anonymous', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('receive_reminders', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('receive_reminders')
        batch_op.drop_column('is_anonymous')

    # ### end Alembic commands ###
