"""Add currency to Transaction model

Revision ID: 3b1e652a8bdf
Revises: 5f6db73dd281
Create Date: 2025-03-06 23:30:51.290719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b1e652a8bdf'
down_revision = '5f6db73dd281'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
