"""Added donor_name to Donation model

Revision ID: 784e7d8665fc
Revises: 
Create Date: 2025-03-03 14:17:21.631111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '784e7d8665fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donor_name', sa.String(), nullable=False, server_default="Anonymous"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_column('donor_name')

    # ### end Alembic commands ###
