"""Add payer_email to Transaction model

Revision ID: a88c21b6ad3b
Revises: 3b1e652a8bdf
Create Date: 2025-03-06 23:35:03.774169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a88c21b6ad3b'
down_revision = '3b1e652a8bdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payer_email', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('payer_email')

    # ### end Alembic commands ###
